version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - overcat
    assignees:
      - overcat
    labels:
      - dependencies